trigger:
- master

variables:
  buildConfiguration: 'Release'

stages:
- stage: Windows
  displayName: Build and Test
  jobs:
  - job: Build
    displayName: Build and Test
    pool:
      vmImage: 'windows-latest'

    steps:

      - task : UseDotNet@2
        displayName: Add .NET 3.1.x SDK
        inputs:
          packageType: 'sdk'
          version: '3.1.x'

      - task : UseDotNet@2
        displayName: Add .NET 5.0.x SDK
        inputs:
          packageType: 'sdk'
          version: '5.0.x'

      - task: DotNetCoreCLI@2
        displayName: Build projects
        inputs:
          command: 'build'
          arguments: '-c $(buildConfiguration) -v n'

      - task: DotNetCoreCLI@2
        displayName: Test projects
        inputs:
          command: 'test'
          arguments: '-c $(buildConfiguration) --no-build'
